### ISSUE TITLE
Video ist not displayed only Audio

### ISSUE THREAD

**Issue by iFadi** [DatabayAG/InteractiveVideo#11]
After Upgrading to ILIAS v5.3.12 we noticed that the InteractiveVideo are not shown anymore, we get only Audio but no Video output (s.screenshot)

We also did test it on a clean ILIAS **v5.3.12** with InteractiveVideo **v2.0.16** Installation, with the same results. The Video which was uploaded has the MP4 Format.

PS: We did apply Workaround patch for making the Interactive Videos work with the Web Access Checker as described in the readme.md

![interactivevideobug](https://user-images.githubusercontent.com/1717456/52404953-eaa9b500-2ad2-11e9-8ae9-0420df7319d3.png)

**Comment by gvollbach** [comment]
@iFadi 
What for a video format are you using? Can you send me a sample file? Does anything (error or warning) come up in the Javascript Console of your browser?

**Comment by iFadi** [comment]
@gvollbach The Video Format we used is .mp4
The Chrome Console does not show any kind of errors. (s.screenshot), here is a sample about 30seconds of the video: https://www.dropbox.com/s/os8g5nfwuo6v2wv/schule.mp4?dl=0

<img width="1421" alt="Bildschirmfoto 2019-03-11 um 10 24 54" src="https://user-images.githubusercontent.com/1717456/54109691-03fe9380-43e8-11e9-8eba-166dff5f4601.png">

**Comment by gvollbach** [comment]
@iFadi Your video format is an mpeg-4

![mediainfo](https://user-images.githubusercontent.com/10603233/54110155-ed087300-43e0-11e9-8336-e5daf47c9f10.png)

The InteractiveVideo needs an h264/AVC video format, to stream the file correctly, please convert your video to a correct format, then plugin should work as expected.
