### ISSUE TITLE
Failed to load resource: the server responded with a status of 416 (Requested Range Not Satisfiable)

### ISSUE THREAD

**Issue by JupytersRedDot** [DatabayAG/InteractiveVideo#21]
I suspect this is more an issue with our server, though I am out of ideas what it could be. 
Until recently everything was fine, the plugin was working as expected. Now all our videos only play for  about 4 seconds and none of the comment tags are working. The only clues I get are from the Browser console:
**Request URL:** https:***.mp4?il_wac_token=c2fcf33264de6b703d88cbbecb38176dddf3a1dc&il_wac_ttl=3&il_wac_ts=1590566370
**Status Code:** 416 Requested Range Not Satisfiable
**Accept-Ranges**: 0-153198
**Cache-Control:** no-store, no-cache, must-revalidate
**Connection:** close
**Content-Description:** access_denied.mp4
**Content-Disposition:** inline; filename="access_denied.mp4"
**Content-Length:** 0
**Content-Range:** bytes 0-153197/153198

Any suggestions to the cause ?

**Comment by gvollbach** [comment]
Do you have the WAC patch applied as mentioned here: https://github.com/DatabayAG/InteractiveVideo#workaround-patch-for-making-the-interactive-videos-work-with-the-web-access-checker

**Comment by JupytersRedDot** [comment]
@gvollbach Thank you very much, it helped. This sounds like something that wouldn't hurt to be in the source code anyways. Are the Ilias developers aware of this? I try to keep direkt code hacks to a minimum on our instance ...

**Comment by gvollbach** [comment]
Great, glad I could help.

Yes the maintainer is aware of this, but since this is a workaround for a plugin which is not used by all ILIAS users, this should not be in the core, in my opinion.

Since your problem is solved, I close this issue.
