### ISSUE TITLE
icompatible use of global $DIC for ILIAS 5.1

### ISSUE THREAD

**Issue by level420** [DatabayAG/InteractiveVideo#30]
In several places $DIC is used, which is not available in ILIAS 5.1.

Found at following places:

https://github.com/DatabayAG/InteractiveVideo/blob/master/classes/class.ilObjInteractiveVideoGUI.php#L2738-L2741
https://github.com/DatabayAG/InteractiveVideo/blob/master/classes/class.ilObjInteractiveVideo.php#L1144-L1152
https://github.com/DatabayAG/InteractiveVideo/blob/master/classes/class.ilObjInteractiveVideo.php#L1173-L1176
https://github.com/DatabayAG/InteractiveVideo/blob/master/classes/class.ilInteractiveVideoCommentsTableGUI.php#L25
https://github.com/DatabayAG/InteractiveVideo/blob/master/classes/class.ilInteractiveVideoCommentsTableGUI.php#L45-L47
https://github.com/DatabayAG/InteractiveVideo/blob/master/classes/class.ilInteractiveVideoCommentsTableGUI.php#L127

**Comment by gvollbach** [comment]
Thanks for your report, please use the branch release_1 for ILIAS 5.1, I will change the compatible version in the plugin.php of the master branch accordingly.

**Comment by level420** [comment]
Oh. That wasn’t my intention!
It would be simple to leave the 5.1 compatibility in by simply replacing $DIC in this cases by using the still abailable global $ilUser.
