### ISSUE TITLE
Fehler beim Kopieren - Return value of SimpleChoiceQuestion::getShowBestSolutionText() must be of the type string

### ISSUE THREAD

**Issue by iFadi** [DatabayAG/InteractiveVideo#38]
Beim kopieren von einem Interakiven Video Objekt zu einem anderen Kurs wird folgender Fehler geworfen:

`[44579] [2021-10-05 09:06:39.353071] lunih_root.ERROR: ilErrorHandling::{closure}:50 0 Return value of SimpleChoiceQuestion::getShowBestSolutionText() must be of the type string, null returned in /srv/ilias/ILIAS/Customizing/global/plugins/Services/Repository/RepositoryObject/InteractiveVideo/classes/class.SimpleChoiceQuestion.php:1529#0 /srv/ilias/ILIAS/Customizing/global/plugins/Services/Repository/RepositoryObject/InteractiveVideo/classes/class.SimpleChoiceQuestion.php(617): SimpleChoiceQuestion->getShowBestSolutionText()
#1 /srv/ilias/ILIAS/Customizing/global/plugins/Services/Repository/RepositoryObject/InteractiveVideo/classes/class.SimpleChoiceQuestion.php(567): SimpleChoiceQuestion->create()
#2 /srv/ilias/ILIAS/Customizing/global/plugins/Services/Repository/RepositoryObject/InteractiveVideo/classes/class.ilObjComment.php(423): SimpleChoiceQuestion->cloneQuestionObject(1600, '1821')
#3 /srv/ilias/ILIAS/Customizing/global/plugins/Services/Repository/RepositoryObject/InteractiveVideo/classes/class.ilObjInteractiveVideo.php(475): ilObjComment->cloneTutorComments(176607, 216475)
#4 /srv/ilias/ILIAS/Services/Object/classes/class.ilObject2.php(403): ilObjInteractiveVideo->doCloneObject(Object(ilObjInteractiveVideo), '75950', 78435)             
#5 /srv/ilias/ILIAS/Services/Object/classes/class.ilObjectCopyGUI.php(1050): ilObject2->cloneObject('75950', 78435)                                                   
#6 /srv/ilias/ILIAS/Services/Object/classes/class.ilObjectCopyGUI.php(981): ilObjectCopyGUI->copyMultipleNonContainer(Array)                                          
#7 /srv/ilias/ILIAS/Services/Object/classes/class.ilObjectCopyGUI.php(609): ilObjectCopyGUI->copySingleObject()                                                       
#8 /srv/ilias/ILIAS/Services/Object/classes/class.ilObjectCopyGUI.php(164): ilObjectCopyGUI->saveTarget()                                                             
#9 /srv/ilias/ILIAS/Services/UICore/classes/class.ilCtrl.php(203): ilObjectCopyGUI->executeCommand()                                                                  
#10 /srv/ilias/ILIAS/Modules/Course/classes/class.ilObjCourseGUI.php(2463): ilCtrl->forwardCommand(Object(ilObjectCopyGUI))                                           
#11 /srv/ilias/ILIAS/Services/UICore/classes/class.ilCtrl.php(203): ilObjCourseGUI->executeCommand()                                                                  
#12 /srv/ilias/ILIAS/Services/Repository/classes/class.ilRepositoryGUI.php(374): ilCtrl->forwardCommand(Object(ilObjCourseGUI))                                       
#13 /srv/ilias/ILIAS/Services/Repository/classes/class.ilRepositoryGUI.php(336): ilRepositoryGUI->show()                                                              
#14 /srv/ilias/ILIAS/Services/UICore/classes/class.ilCtrl.php(203): ilRepositoryGUI->executeCommand()                                                                 
#15 /srv/ilias/ILIAS/Services/UICore/classes/class.ilCtrl.php(164): ilCtrl->forwardCommand(Object(ilRepositoryGUI))                                                   
#16 /srv/ilias/ILIAS/ilias.php(20): ilCtrl->callBaseClass()
#17 {main}`

Das Objekt wird angezeigt, wo es kopiert wurde, aber das Fragen-Fenster ist leer bzw. die Fragen sind defekt.

---- 
ILIAS Version: v6.11
InteractiveVideo: 2.6.0
PHP 7.3.29-1~deb10u1 (cli) (built: Jul  2 2021 04:04:33) ( NTS )

**Comment by gvollbach** [comment]
Should be fixed in branch 6_x
