### ISSUE TITLE
416 Requested Range Not Satisfiable / Update auf v5.3.0

### ISSUE THREAD

**Issue by kinimodmeyer** [DatabayAG/InteractiveVideo#4]
Hallo zusammen,

wir bekommen bei der Betrachtung von hochgeladenen Videos (entfernte z.B. via Youtube funktionieren ohne Probleme) beim Request z.B. nach 2 Sekunden laden: 416 Requested Range Not Satisfiable

Habt ihr eine Idee wo es hier klemmen könnte?
Wir lassen das ganze auf 5.3 laufen. Wann wird es hier ein Update geben?

Ich vermute nicht das der Fehler unbedingt mit der Version zusammenhängt.

**Comment by gvollbach** [comment]
Hi,
das liegt wenn dann an dem Webserver auf dem das Video liegt, das hat mir soweit mir bekannt weder mit Ilias oder dem InteractiveVideo zu tun. Aber mehr Infos zu dem Problem hab ich da leider auch nicht, mir ist eine andere Institution bekannt, bei denen das auftrat, aber da löste sich das Problem irgendwann von selbst.

Update für 5.3 ist aktuell in Entwicklung.

**Comment by kinimodmeyer** [comment]
Folgendes in die .htaccess hat das Problem behoben:
Header set Accept-Ranges none
RequestHeader unset Range

> Update für 5.3 ist aktuell in Entwicklung.

sehr schön 👍

**Comment by gvollbach** [comment]
Da dann soweit ja hier nichts mehr zu tun ist machen wir mal zu. Und danke für die Problemlösung, vielleicht hilft das ja dem einen oder anderen weiter.

**Comment by kinimodmeyer** [comment]
Update auf v5.3.0 steht noch aus aber sonst ja :+1:
