### ISSUE TITLE
Error when installing:  Row size too large

### ISSUE THREAD

**Issue by haary** [DatabayAG/InteractiveVideo#49]
When installing the plugin in Ilias 7.26 I get the error "1118 Row size too large."

Here's the  the error log:

```
PDOException thrown with message "SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This 
includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"

Stacktrace:
#15 PDOException in /var/www/htdocs/Services/Database/classes/PDO/Manager/class.ilDBPdoManager.php:306
#14 PDO:exec in /var/www/htdocs/Services/Database/classes/PDO/Manager/class.ilDBPdoManager.php:306
#13 ilDBPdoManager:alterTable in /var/www/htdocs/Services/Database/classes/PDO/class.ilDBPdo.php:468
#12 ilDBPdo:addTableColumn in /var/www/htdocs/Services/Database/classes/class.ilDBUpdate.php:504
#11 eval in /var/www/htdocs/Services/Database/classes/class.ilDBUpdate.php:504
#10 ilDBUpdate:applyUpdateNr in /var/www/htdocs/Services/Database/classes/class.ilDBUpdate.php:371
#9 ilDBUpdate:applyUpdate in /var/www/htdocs/Services/Component/classes/class.ilPlugin.php:526
#8 ilPlugin:updateDatabase in /var/www/htdocs/Services/Component/classes/class.ilPlugin.php:1087
#7 ilPlugin:update in /var/www/htdocs/Services/Component/classes/class.ilObjComponentSettingsGUI.php:507
#6 ilObjComponentSettingsGUI:update in /var/www/htdocs/Services/Component/classes/class.ilObjComponentSettingsGUI.php:502
#5 ilObjComponentSettingsGUI:updatePlugin in /var/www/htdocs/Services/Component/classes/class.ilObjComponentSettingsGUI.php:123
#4 ilObjComponentSettingsGUI:executeCommand in /var/www/htdocs/Services/UICore/classes/class.ilCtrl.php:217
#3 ilCtrl:forwardCommand in /var/www/htdocs/Services/Administration/classes/class.ilAdministrationGUI.php:246
#2 ilAdministrationGUI:executeCommand in /var/www/htdocs/Services/UICore/classes/class.ilCtrl.php:217
#1 ilCtrl:forwardCommand in /var/www/htdocs/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /var/www/htdocs/ilias.php:23
```

**Comment by nmatuschek** [comment]
I can not reproduce this and it's not fixable in the code.  Is it a clean new  ILIAS  installation and could i be you created the database manually? Please check the row_format of the database tables. I suggest to set it to "dynamic".  Maybe this could solve the problem. 
![innodb_default_row_format](https://github.com/DatabayAG/InteractiveVideo/assets/2510394/4656ad3d-e011-4b5a-b345-d885736c6eab)

**Comment by haary** [comment]
All tables already  have ROW_FORMAT "dynamic", so that seems not to be the cause of the problem. Is is an old installation, upgradet from 5.4.26

**Comment by nmatuschek** [comment]
Ok. It seems like there are some updates mimssing.  
- > Navigate to the plugin administration in ILIAS. 
-> Select "configure" from the action menu of the InteractiveVideo-Plugin 

On the Configure overview you can select the db updates for the features you would like to use.     
![Bildschirmfoto vom 2023-12-15 11-56-14](https://github.com/DatabayAG/InteractiveVideo/assets/2510394/d4692804-5826-48e2-9910-e4647d1a5ab9)

**Comment by haary** [comment]
> Ok. It seems like there are some updates mimssing.
> 
>     * > Navigate to the plugin administration in ILIAS.
>       > -> Select "configure" from the action menu of the InteractiveVideo-Plugin

Since the installation and activation fails in the first place I can't configure the plugin.

**Comment by dmundra** [comment]
Create a new issue in mantis https://mantis.ilias.de/my_view_page.php for 'Interactive Video' e.g. https://mantis.ilias.de/view.php?id=39392

**Comment by Stefan-Schulze-SIMTEVA** [comment]
Any update on this? On the Mantis Bugtracker there is no update, and i have the same error. I also commented in the open Bug
https://mantis.ilias.de/view.php?id=40117#bugnotes

**Comment by gvollbach** [comment]
This is not a bug in the IV Plugin, your DB table has to be set to DYNAMIC:
ALTER TABLE  'name_of_the_table_which_throws_the_error'  ROW_FORMAT=DYNAMIC;

**Comment by haary** [comment]
> This is not a bug in the IV Plugin, your DB table has to be set to DYNAMIC: ALTER TABLE 'name_of_the_table_which_throws_the_error' ROW_FORMAT=DYNAMIC;

As I commented  here https://github.com/DatabayAG/InteractiveVideo/issues/49#issuecomment-1855425477 all tables are already DYNAMIC, so this seems not to be cause for the problem

**Comment by rschenk0** [comment]
If you get above error anywhere in ILIAS you are either not on tables using ROW_FORMAT=DYNAMIC or you are using 4-Byte UTF-8 Collations like "utf8mb4_unicode_ci" instead of "utf8mb3_unicode_ci" for your tables which is not supported at all. You can use provided script to convert a complete ILIAS DB to UTF-8 3byte encoding.
[convert_tables_to_utf8_unicode.sh.txt](https://github.com/user-attachments/files/16392818/convert_tables_to_utf8_unicode.sh.txt)
