### ISSUE TITLE
Fehler beim Löschen von Interaktiven Videos aus dem ILIAS-Papierkorb.

### ISSUE THREAD

**Issue by christianfliegnergoe** [DatabayAG/InteractiveVideo#69]
Wenn man Interaktive Videos löscht oder die bereits existierenden Videos im Papierkorb löschen will, erhält man folgenden Fehler

TypeError thrown with message "Return value of ilObjInteractiveVideo::getVideoSourceObject() must implement interface ilInteractiveVideoSource, null returned"

Stacktrace:
#12 TypeError in /srv/www/agricareernet-ilias8/Customizing/global/plugins/Services/Repository/RepositoryObject/InteractiveVideo/classes/class.ilObjInteractiveVideo.php:99
#11 ilObjInteractiveVideo:getVideoSourceObject in /srv/www/agricareernet-ilias8/Customizing/global/plugins/Services/Repository/RepositoryObject/InteractiveVideo/classes/class.ilObjInteractiveVideo.php:130
#10 ilObjInteractiveVideo:doRead in /srv/www/agricareernet-ilias8/Services/Object/classes/class.ilObject2.php:42
#9 ilObject2:read in /srv/www/agricareernet-ilias8/Services/Object/classes/class.ilObjectFactory.php:196
#8 ilObjectFactory:getInstanceByRefId in /srv/www/agricareernet-ilias8/Services/Repository/Trash/class.ilRepUtil.php:246
#7 ilRepUtil:removeObjectsFromSystem in /srv/www/agricareernet-ilias8/Services/Repository/Trash/class.ilRepositoryTrashGUI.php:441
#6 ilRepositoryTrashGUI:removeObjectsFromSystem in /srv/www/agricareernet-ilias8/Services/Container/classes/class.ilContainerGUI.php:2596
#5 ilContainerGUI:removeFromSystemObject in /srv/www/agricareernet-ilias8/Modules/RootFolder/classes/class.ilObjRootFolderGUI.php:185
#4 ilObjRootFolderGUI:executeCommand in /srv/www/agricareernet-ilias8/Services/UICore/classes/class.ilCtrl.php:203
#3 ilCtrl:forwardCommand in /srv/www/agricareernet-ilias8/Services/Administration/classes/class.ilAdministrationGUI.php:237
#2 ilAdministrationGUI:executeCommand in /srv/www/agricareernet-ilias8/Services/UICore/classes/class.ilCtrl.php:203
#1 ilCtrl:forwardCommand in /srv/www/agricareernet-ilias8/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /srv/www/agricareernet-ilias8/ilias.php:24

Wir verwenden ILIAS 8.13 mit der Plugin-Version 3.5.2

**Comment by gvollbach** [comment]
@christianfliegnergoe Ich habe es gerade einmal bei mir lokal auf einer ILIAS 8 Plattform ausprobiert und kann keine Probleme in der Richtung feststellen. Ein paar Fragen:
- Seid ihr auf einem aktuelle Plugin Stand mit dem IV (Interactive Video) Plugin?
- Passiert das bei allen IV Objekte auf die ihr löscht oder nur bei bestimmten? Was mich verwirrt ist die Aussage: "Interaktive Videos löscht oder die bereits existierenden Videos im Papierkorb löschen will" das sind halt zwei komplett unterschiedliche Abläufe
- Was für Video Quellen haben die IV Objekte?
- Was für Video Quellen hat ihr in Benutzung und habt ihr da vor kurzen Video Quellen gelöscht?

**Comment by christianfliegnergoe** [comment]
Hallo Herr Vollbach,

ich habe nochmals den Code überprüft. In der Tat, war ich versehentlich auf dem git-Branch r8_dev gelandet. Ich habe dies jetzt korrigiert (bin jetzt auf r8). Habe das alte Verzeichnis vorsorglich gelöscht.

Dann neu runter geladen.

„git clone https://github.com/DatabayAG/InteractiveVideo.git InteractiveVideo --branch r8 --single-branch“

Jetzt kann ich den Fehler besser eingrenzen. Wenn man ein IA Video in den Papierkorb verschiebt, und dann das IA aus dem Papierkorb löschen möchte, kommt folgender Fehler.

***@***.***

Hier wird wieder das besagte Interface vermisst. Die IA sind in einer ILIAS 5.4er Version erzeugt worden und befanden sich während der Migration auf ILIAS 8 im Papierkorb. Möglicherweise fehlen durch den Versionssprung Daten im IA.

***@***.***

Herzliche Grüße
Christian Fliegner


Von: Guido Vollbach ***@***.***>
Gesendet: Freitag, 16. August 2024 11:13
An: DatabayAG/InteractiveVideo ***@***.***>
Cc: Fliegner, Christian ***@***.***>; Mention ***@***.***>
Betreff: Re: [DatabayAG/InteractiveVideo] Fehler beim Löschen von Interaktiven Videos aus dem ILIAS-Papierkorb. (Issue #69)


@christianfliegnergoe<https://github.com/christianfliegnergoe> Ich habe es gerade einmal bei mir lokal auf einer ILIAS 8 Plattform ausprobiert und kann keine Probleme in der Richtung feststellen. Ein paar Fragen:

  *   Seid ihr auf einem aktuelle Plugin Stand mit dem IV (Interactive Video) Plugin?
  *   Passiert das bei allen IV Objekte auf die ihr löscht oder nur bei bestimmten? Was mich verwirrt ist die Aussage: "Interaktive Videos löscht oder die bereits existierenden Videos im Papierkorb löschen will" das sind halt zwei komplett unterschiedliche Abläufe
  *   Was für Video Quellen haben die IV Objekte?
  *   Was für Video Quellen hat ihr in Benutzung und habt ihr da vor kurzen Video Quellen gelöscht?

**Comment by gvollbach** [comment]
Ok, ich vermute die Objekte die bei ihnen Probleme verursachen haben entweder keinen oder einen ungültigen Eintrag als "source_id", könnten sie einmal in der Tabelle rep_robj_xvid_objects schauen ob dort Einträge ohne "source_id" vorhanden sind?

**Comment by christianfliegnergoe** [comment]
Hallo Herr Vollbach,

hier sind die Daten der Tabelle. Die Spalte „source_id“ ist zwar nicht leer, aber ob der Inhalt verarbeitet werden kann erschließt sich mir nicht.

***@***.***

Von: Guido Vollbach ***@***.***>
Gesendet: Freitag, 16. August 2024 12:44
An: DatabayAG/InteractiveVideo ***@***.***>
Cc: Fliegner, Christian ***@***.***>; Mention ***@***.***>
Betreff: Re: [DatabayAG/InteractiveVideo] Fehler beim Löschen von Interaktiven Videos aus dem ILIAS-Papierkorb. (Issue #69)


Ok, ich vermute die Objekte die bei ihnen Probleme verursachen haben entweder keinen oder einen ungültigen Eintrag als "source_id", könnten sie einmal in der Tabelle rep_robj_xvid_objects schauen ob dort Einträge ohne "source_id" vorhanden sind?

**Comment by gvollbach** [comment]
Guten Tag, 

ich vermute sie antworten per eMail und Github verschluckt dann Anhänge, sehe ich leider nichts, aber ich hab die Stelle welche meiner Meinung nach die Probleme verursacht einmal etwas stabiler gestaltet, könnten sie bitte noch einmal einen "git pull" machen und das ganze noch einmal probieren?
Sollte das nicht geholfen haben, schauen sie bitte einmal in ihrer ILIAS Log Datei, dort sollte dann sowas stehen wie:
`ERROR: ilObjInteractiveVideo::doRead:42 No source id give for InteractiveVideo object with the id 123`

**Comment by christianfliegnergoe** [comment]
Hallo Herr Vollbach,

danke für den schnellen Bgugfix(versuch). Ich habe das „git pull“ soeben vorgenommen. Beim Löschen eines IA kommt jetzt ein anderer Fehler. Ich hatte bisher die Fehler immer als Bild geschickt. Da diese aber scheinbar nicht durch kommen, schicke ich die Fehlermeldung aus dem Log als Text.

Die Interface-Meldung scheint durch zu sein. Nun werden jedoch alle möglichen Werte im Typ kritisiert. Die von Ihnen

/srv/log/agricareernet-ilias/agricareernet-ilias_errorlogs/uospb_106.log

TypeError thrown with message "Argument 1 passed to ilObjInteractiveVideo::setIsAnonymized() must be of the type int, null given, called in /srv/www/agricareernet-ilias8/Customizing/global/plugins
/Services/Repository/RepositoryObject/InteractiveVideo/classes/class.ilObjInteractiveVideo.php on line 118"

Stacktrace:
#12 TypeError in /srv/www/agricareernet-ilias8/Customizing/global/plugins/Services/Repository/RepositoryObject/InteractiveVideo/classes/class.ilObjInteractiveVideo.php:848
#11 ilObjInteractiveVideo:setIsAnonymized in /srv/www/agricareernet-ilias8/Customizing/global/plugins/Services/Repository/RepositoryObject/InteractiveVideo/classes/class.ilObjInteractiveVideo.php:
118
#10 ilObjInteractiveVideo:doRead in /srv/www/agricareernet-ilias8/Services/Object/classes/class.ilObject2.php:42
#9 ilObject2:read in /srv/www/agricareernet-ilias8/Services/Object/classes/class.ilObjectFactory.php:196
#8 ilObjectFactory:getInstanceByRefId in /srv/www/agricareernet-ilias8/Services/Repository/Trash/class.ilRepUtil.php:246
#7 ilRepUtil:removeObjectsFromSystem in /srv/www/agricareernet-ilias8/Services/Repository/Trash/class.ilRepositoryTrashGUI.php:441
#6 ilRepositoryTrashGUI:removeObjectsFromSystem in /srv/www/agricareernet-ilias8/Services/Container/classes/class.ilContainerGUI.php:2596
#5 ilContainerGUI:removeFromSystemObject in /srv/www/agricareernet-ilias8/Modules/RootFolder/classes/class.ilObjRootFolderGUI.php:185
#4 ilObjRootFolderGUI:executeCommand in /srv/www/agricareernet-ilias8/Services/UICore/classes/class.ilCtrl.php:203
#3 ilCtrl:forwardCommand in /srv/www/agricareernet-ilias8/Services/Administration/classes/class.ilAdministrationGUI.php:237
#2 ilAdministrationGUI:executeCommand in /srv/www/agricareernet-ilias8/Services/UICore/classes/class.ilCtrl.php:203
#1 ilCtrl:forwardCommand in /srv/www/agricareernet-ilias8/Services/UICore/classes/class.ilCtrl.php:178
#0 ilCtrl:callBaseClass in /srv/www/agricareernet-ilias8/ilias.php:24


Herzliche Grüße
Christian Fliegner

Von: Guido Vollbach ***@***.***>
Gesendet: Freitag, 16. August 2024 13:03
An: DatabayAG/InteractiveVideo ***@***.***>
Cc: Fliegner, Christian ***@***.***>; Mention ***@***.***>
Betreff: Re: [DatabayAG/InteractiveVideo] Fehler beim Löschen von Interaktiven Videos aus dem ILIAS-Papierkorb. (Issue #69)


Guten Tag,

ich vermute sie antworten per eMail und Github verschluckt dann Anhänge, sehe ich leider nichts, aber ich hab die Stelle welche meiner Meinung nach die Probleme verursacht einmal etwas stabiler gestaltet, könnten sie bitte noch einmal einen "git pull" machen und das ganze noch einmal probieren?
Sollte das nicht geholfen haben, schauen sie bitte einmal in ihrer ILIAS Log Datei, dort sollte dann sowas stehen wie:
ERROR: ilObjInteractiveVideo::doRead:42 No source id give for InteractiveVideo object with the id 123

**Comment by gvollbach** [comment]
Ja das sieht irgendwie so aus, als wäre dort unvollständige Daten vorhanden, ich vermute fast, die Objekte haben wahrscheinlich noch Verweise in der "obj_data" Tabelle, aber wahrscheinlich keine Daten mehr in der "rep_robj_xvid_objects" zumindest scheint es so. Am besten schreiben sie mir einmal direkt eine Mail, dann können wir einfacher Informationen austauschen. Ich werde aber erst dann nächste Woche dazu kommen mich damit noch einmal genauer zu beschäftigen.

**Comment by gvollbach** [comment]
Since this problem seems more like a inconsistent data structure in the ILIAS database I close this issue. If someone should encounter a similar problem please use the system check to validate that your database is in a consistent state.
