### ISSUE TITLE
DB Migration/Fix für PHP8.0

### ISSUE THREAD

**Issue by Hufschmidt** [DatabayAG/InteractiveVideo#75]
We stumbled upon the following error when using the ILIAS8 version (Branch: r8) with PHP8.0, getting (among other things) the following error:

```
TypeError thrown with message "SimpleChoiceQuestion::setCompulsoryQuestion(): Argument #1 ($compulsory_question) must be of type int, null given, called in [...]/InteractiveVideo/classes/questions/class.SimpleChoiceQuestion.php on line 379"

Stacktrace:
#16 TypeError in [...]/InteractiveVideo/classes/questions/class.SimpleChoiceQuestion.php:1186
#15 SimpleChoiceQuestion:setCompulsoryQuestion in [...]/InteractiveVideo/classes/questions/class.SimpleChoiceQuestion.php:379
#14 SimpleChoiceQuestion:cloneQuestionObject in [...]/InteractiveVideo/classes/class.ilObjComment.php:316
#13 ilObjComment:cloneTutorComments in [...]/InteractiveVideo/classes/class.ilObjInteractiveVideo.php:462
[...]
```

Which we fixed by updating the values of (*legacy?*) DB entries, eg. from NULL to 0 or '':
```
MariaDB [...]> update rep_robj_xvid_question set compulsory_question = 0 where compulsory_question is null;
Query OK, 3374 rows affected (0.049 sec)
Rows matched: 3374  Changed: 3374  Warnings: 0

MariaDB [...]> update rep_robj_xvid_question set show_best_solution_text = '' where show_best_solution_text is null;
Query OK, 3374 rows affected (0.053 sec)
Rows matched: 3374  Changed: 3374  Warnings: 0
```
Note: 
- Newly created entries seem to be created with correct defaults, eg. 0 or '' instead of null, so these changes are probably _legacy_ entries.
- There might be other columns that are NULL but should not, but this alone fixed issue with Questions be uneditable and objects not being cloneable.

Maybe this could be added as DB-Update Step similar to DB-Update Step `#84` in the master branch, which is currently not present in r8 or r8_dev also it seems.

**Comment by gvollbach** [comment]
@Hufschmidt I fixed some things similar to this last month, could you please pull the latest version of the r8 branch and try this again? Thx.

**Comment by Hufschmidt** [comment]
LGTM. Tested [*] and seems to work as intended.

---

[*] Reset one single-choice question from empty-string to NULL. Could edit and save question without errors. Updated question also has correct value again (empty string instead of NULL). :+1:

**Comment by gvollbach** [comment]
@Hufschmidt Great, thanks for the feedback.
